language: elixir
otp_release:
  - 18.3
  - 19.2
elixir:
  - 1.4.0
  - 1.3.4
  - 1.2.6
  - 1.1.1
matrix:
  exclude:
    - elixir: 1.1.1
      otp_release: 19.2
  include:
    - elixir: 1.1.1
      otp_release: 17.5
      env: COVER=mix test --cover
sudo: required
env:
  - COVER=mix coveralls.travis
cache:
  directories:
    - ~/kafka
before_install:
  - scripts/install_kafka.sh
before_script:
  - scripts/start_kafka.sh
script:
  - MIX_ENV=test mix deps.compile
  - mix test --include integration --include consumer_group --include server_0_p_9_p_0; MIX_ENV=test ${COVER} --include integration --include consumer_group --include server_0_p_9_p_0
