language: elixir
otp_release:
  - 17.5
  - 18.2.1
elixir:
  - 1.3.0
  - 1.2.6
  - 1.2.5
  - 1.2.4
  - 1.2.3
  - 1.1.1
  - 1.0.4
matrix:
  exclude:
    - elixir: 1.0.4
      otp_release: 18.2.1
    - elixir: 1.2.3
      otp_release: 17.5
    - elixir: 1.2.4
      otp_release: 17.5
    - elixir: 1.2.5
      otp_release: 17.5
    - elixir: 1.2.6
      otp_release: 17.5
    - elixir: 1.3.0
      otp_release: 17.5
sudo: false
cache:
  directories:
    - ~/kafka
before_install:
  - scripts/install_kafka.sh
before_script:
  - scripts/start_kafka.sh
script:
  - mix test --include integration --include consumer_group --include server_0_p_9_p_0; mix test --include integration --include consumer_group --include server_0_p_9_p_0
